### ISSUE TITLE
Missing Express boilerplate code

### ISSUE THREAD

**Issue by davidfekke** [nerikh/ajax-firebase-promise#1]
Eric,

I can see in your `index.js` file that you defined routes for `/users/user-update/` and `/users/user-update/`, but I do not see where express has been initialized or firebase.

**Comment by nerikh** [comment]
David,

The index.js is a really long file, I thought I'd simply send you the code
that has the problems.  There are plenty routes rendering.  Do you want me
to add to the index.js all the initializations?



Nils 'Erik' Hendrick
High Performance Websites
T 904.999.4532
bodigiti <http://bodigiti.com/> | 6 critical web design areas
<http://bodigiti.com/six-web-design-areas>

**Comment by davidfekke** [comment]
Ok
